from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
db = client["book_recommendation"]

books = {
    "happy": [
        {"title": "Waiting for Godalming", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0552147427.01.MZZZZZZZ.jpg"},
        {"title": "The Forest House", "genre": "Fantasy Fiction", "image_url": "http://images.amazon.com/images/P/0451454243.01.MZZZZZZZ.jpg"},
        {"title": "The Stars Shine Down", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0446364762.01.MZZZZZZZ.jpg"},
        {"title": "The Secret Garden", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0812505018.01.MZZZZZZZ.jpg"},
        {"title": "The Little Prince", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/0156528207.01.MZZZZZZZ.jpg"},
        {"title": "Harry Potter and the Sorcerer's Stone", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/059035342X.01.MZZZZZZZ.jpg"},
        {"title": "The Hobbit", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/0395177111.01.MZZZZZZZ.jpg"},
        {"title": "The Bad Beginning (A Series of Unfortunate Events, Book 1)", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/0064407667.01.MZZZZZZZ.jpg"},
        {"title": "The Sorcerer's Companion: A Guide to the Magical World of Harry Potter", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/0767908473.01.MZZZZZZZ.jpg"},
        {"title": "Titan", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/0425049981.01.MZZZZZZZ.jpg"},
        {"title": "Sunwing", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/0689832877.01.MZZZZZZZ.jpg"},
        {"title": "Black Thorn, White Rose", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/068813713X.01.MZZZZZZZ.jpg"},
        {"title": "Born of the Sun", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/0453006663.01.MZZZZZZZ.jpg"},
        {"title": "The White Puma", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/1558175326.01.MZZZZZZZ.jpg"},
        {"title": "Enchantment", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/0345416880.01.MZZZZZZZ.jpg"},
        {"title": "The Hork-Bajir Chronicles (Animorphs Series)", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/0439042917.01.MZZZZZZZ.jpg"},
        {"title": "The Rescue", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0446525502.01.MZZZZZZZ.jpg"},
        {"title": "A Map of the World", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0385500769.01.MZZZZZZZ.jpg"},
        {"title": "Vinegar Hill", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0688180639.01.MZZZZZZZ.jpg"},
        {"title": "Angel Falls", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0609605925.01.MZZZZZZZ.jpg"},
        {"title": "The Saving Graces: A Novel", "genre": "Drama", "image_url": "http://images.amazon.com/images/P/0060191929.01.MZZZZZZZ.jpg"},
        {"title": "The Vineyard: A Novel", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0684864843.01.MZZZZZZZ.jpg"},
        {"title": "The Looking Glass: A Novel", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0684867818.01.MZZZZZZZ.jpg"},
        {"title": "The Promise Remains", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0684868911.01.MZZZZZZZ.jpg"},
        {"title": "The Villa", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/052594463X.01.MZZZZZZZ.jpg"},
        {"title": "In This Mountain", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/039304016X.01.MZZZZZZZ.jpg"},
        {"title": "Blue Heaven", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0140107649.01.MZZZZZZZ.jpg"},
        {"title": "One Heart", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/1570717257.01.MZZZZZZZ.jpg"},
        {"title": "Anne of Green Gables", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/055321313X.01.MZZZZZZZ.jpg"},
        {"title": "Marriage by the Book", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/1551666987.01.MZZZZZZZ.jpg"},
        {"title": "The Bride's Rescuer", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/0373226918.01.MZZZZZZZ.jpg"},
        {"title": "Twin Blessings", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/0373871562.01.MZZZZZZZ.jpg"},
        {"title": "Whisper to Me of Love", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/0380752115.01.MZZZZZZZ.jpg"},
        {"title": "Tender Triumph", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/0671614568.01.MZZZZZZZ.jpg"},
        {"title": "A Minor Indiscretion", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/0373250339.01.MZZZZZZZ.jpg"},
        {"title": "For Better, for Worse", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/0380820447.01.MZZZZZZZ.jpg"},
        {"title": "Geek Love", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/0446391301.01.MZZZZZZZ.jpg"},
        {"title": "Golden Cup", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/0440130913.01.MZZZZZZZ.jpg"},
        {"title": "One True Love? (Harlequin Flipside, No. 2)", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/0373441762.01.MZZZZZZZ.jpg"},
        {"title": "A Room with a View", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/0679724761.01.MZZZZZZZ.jpg"},
        {"title": "Fitcher's Brides", "genre": "Romance", "image_url": "http://images.amazon.com/images/P/0765301954.01.MZZZZZZZ.jpg"},
        {"title": "The Notebook", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0802135064.01.MZZZZZZZ.jpg"},
        {"title": "Citizens: A Chronicle of the French Revolution", "genre": "Historical Fiction", "image_url": "http://images.amazon.com/images/P/0679726101.01.MZZZZZZZ.jpg"},
        {"title": "Stone Butch Blues", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/156341029X.01.MZZZZZZZ.jpg"},
        {"title": "Stardust", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/0060934719.01.MZZZZZZZ.jpg"},
        {"title": "The Beans of Egypt, Maine", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0446300101.01.MZZZZZZZ.jpg"},
        {"title": "Slow River", "genre": "Fiction", "image_url": "http://images.amazon.com/images/P/0345395379.01.MZZZZZZZ.jpg"},
        {"title": "The Space Merchants", "genre": "Science Fiction", "image_url": "http://images.amazon.com/images/P/0312749511.01.MZZZZZZZ.jpg"},
        {"title": "Dreamsnake", "genre": "Science Fiction", "image_url": "http://images.amazon.com/images/P/0395264707.01.MZZZZZZZ.jpg"},
        {"title": "The Kite Runner", "genre": "Historical Fiction", "image_url": "http://images.amazon.com/images/P/1573222453.01.MZZZZZZZ.jpg"},
        {"title": "Changer", "genre": "Fantasy", "image_url": "http://images.amazon.com/images/P/0805062971.01.MZZZZZZZ.jpg"},
    ],
    "sad": [
        {"title": "Life’s Little Instruction Book", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/0805062971.01.MZZZZZZZ.jpg"},
        {"title": "Love, Medicine, and Miracles", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/0060154969.01.MZZZZZZZ.jpg"},
        {"title": "Getting Well Again", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/0553259865.01.MZZZZZZZ.jpg"},
        {"title": "The Therapeutic Touch", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/067176537X.01.MZZZZZZZ.jpg"},
        {"title": "Rich Dad, Poor Dad: What the Rich Teach Their Kids About Money--That the Poor and Middle Class Do Not!", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/0446677450.01.MZZZZZZZ.jpg"},
        {"title": "Creating Wealth: Retire in Ten Years Using Allen's Seven Principles of Wealth!", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/0671621009.01.MZZZZZZZ.jpg"},
        {"title": "Keep It Simple: And Get More Out of Life", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/0002740230.01.MZZZZZZZ.jpg"},
        {"title": "If Singleness Is a Gift, What's the Return Policy?", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/0785263292.01.MZZZZZZZ.jpg"},
        {"title": "Always Daddy's Girl: Understanding Your Father's Impact on Who You Are", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/0830714014.01.MZZZZZZZ.jpg"},
        {"title": "The 7 Habits of Highly Effective People", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/1883219027.01.MZZZZZZZ.jpg"},
        {"title": "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/0735211299.01.MZZZZZZZ.jpg"},
        {"title": "The Power of Now: A Guide to Spiritual Enlightenment", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/1577311523.01.MZZZZZZZ.jpg"},
        {"title": "Self Analysis", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/0884041093.01.MZZZZZZZ.jpg"},
        {"title": "Come Before Winter and Share My Hope", "genre": "Self-Help", "image_url": "http://images.amazon.com/images/P/0842304770.01.MZZZZZZZ.jpg"},
        {"title": "More George W. Bushisms", "genre": "Comedy", "image_url": "http://images.amazon.com/images/P/0743251008.01.MZZZZZZZ.jpg"},
        {"title": "The World's Stupidest Laws", "genre": "Comedy", "image_url": "http://images.amazon.com/images/P/185479549X.01.MZZZZZZZ.jpg"},
        {"title": "The World's Stupidest Signs", "genre": "Comedy", "image_url": "http://images.amazon.com/images/P/1854795554.01.MZZZZZZZ.jpg"},
        {"title": "SO LONG AND THANKS FOR ALL THE FISH", "genre": "Comedy", "image_url": "http://images.amazon.com/images/P/0671745530.01.MZZZZZZZ.jpg"},
        {"title": "The Amazing Adventures of Kavalier & Clay", "genre": "Comedy", "image_url": "http://images.amazon.com/images/P/0312282990.01.MZZZZZZZ.jpg"},
        {"title": "The Real Mother Goose", "genre": "Comedy", "image_url": "http://images.amazon.com/images/P/0026890380.01.MZZZZZZZ.jpg"},
        {"title": "One Fish Two Fish Red Fish Blue Fish", "genre": "Comedy", "image_url": "http://images.amazon.com/images/P/0394800133.01.MZZZZZZZ.jpg"},
        {"title": "The Chocolate Korndog", "genre": "Comedy", "image_url": "http://images.amazon.com/images/P/074141127X.01.MZZZZZZZ.jpg"},
        {"title": "Eeyore's Little Book of Gloom", "genre": "Comedy", "image_url": "http://images.amazon.com/images/P/0416196772.01.MZZZZZZZ.jpg"},
        {"title": "Crazy from the Heat", "genre": "Comedy", "image_url": "http://images.amazon.com/images/P/0786889470.01.MZZZZZZZ.jpg"},
        {"title": "Expecting Someone Taller", "genre": "Comedy", "image_url": "http://images.amazon.com/images/P/044122332X.01.MZZZZZZZ.jpg"},
        {"title": "Moby-Dick", "genre": "Adventure", "image_url": "http://images.amazon.com/images/P/0140390847.01.MZZZZZZZ.jpg"},
        {"title": "Life of Pi", "genre": "Adventure", "image_url": "http://images.amazon.com/images/P/0151008116.01.MZZZZZZZ.jpg"},
        {"title": "Neverwhere", "genre": "Adventure", "image_url": "http://images.amazon.com/images/P/0380973634.01.MZZZZZZZ.jpg"},
        {"title": "The Call of the Wild", "genre": "Adventure", "image_url": "http://images.amazon.com/images/P/0451527038.01.MZZZZZZZ.jpg"},
        {"title": "The Phantom Tollbooth", "genre": "Adventure", "image_url": "http://images.amazon.com/images/P/0394815009.01.MZZZZZZZ.jpg"},
        {"title": "Tracks", "genre": "Adventure", "image_url": "http://images.amazon.com/images/P/0060972459.01.MZZZZZZZ.jpg"},
        {"title": "Daughter of Fortune", "genre": "Adventure", "image_url": "http://images.amazon.com/images/P/038082101X.01.MZZZZZZZ.jpg"},
        {"title": "Becoming a Man", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/0062507249.01.MZZZZZZZ.jpg"},
        {"title": "Anne Frank: The Diary of a Young Girl", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/0553296981.01.MZZZZZZZ.jpg"},
        {"title": "Long Walk to Freedom", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/0316548189.01.MZZZZZZZ.jpg"},
        {"title": "Gandhi An Autobiography: The Story of My Experiments With Truth", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/0807059099.01.MZZZZZZZ.jpg"},
        {"title": "Benjamin Franklin: An American Life", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/074353364X.01.MZZZZZZZ.jpg"},
        {"title": "Born to Run", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/044010694X.01.MZZZZZZZ.jpg"},
        {"title": "Wilbur and Orville: A Biography of the Wright Brothers", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/039454269X.01.MZZZZZZZ.jpg"},
        {"title": "Madame Curie: A Biography", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/0306810387.01.MZZZZZZZ.jpg"},
        {"title": "The Years of Lyndon Johnson", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/067973371X.01.MZZZZZZZ.jpg"},
        {"title": "Elvis Presley", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/0670031747.01.MZZZZZZZ.jpg"},
        {"title": "The Man Who Knew Infinity", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/0671750615.01.MZZZZZZZ.jpg"},
        {"title": "Alan Turing: The Enigma", "genre": "Biography", "image_url": "http://images.amazon.com/images/P/0802775802.01.MZZZZZZZ.jpg"},
    ],
    "angry": [
        {"title": "How Not to Say What You Mean: A Dictionary of Euphemisms", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0198604025.01.MZZZZZZZ.jpg"},
        {"title": "College Majors and Careers: A Resource Guide for Effective Life Planning", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0894342789.01.MZZZZZZZ.jpg"},
        {"title": "How to Win Friends and Influence People", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0671027034.01.MZZZZZZZ.jpg"},
        {"title": "The Grace and Truth Paradox: Responding with Christlike Balance", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/1590520653.01.MZZZZZZZ.jpg"},
        {"title": "Just Here Trying to Save a Few Lives", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0446677574.01.MZZZZZZZ.jpg"},
        {"title": "So That Others May Live: Caroline Hebard & Her Search-And-Rescue Dogs", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0553574833.01.MZZZZZZZ.jpg"},
        {"title": "I Thought My Father Was God: And Other True Tales from NPR's National Story Project", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0312421001.01.MZZZZZZZ.jpg"},
        {"title": "The Best Thing I Ever Did for My Marriage: 50 Real Life Stories", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/1590521994.01.MZZZZZZZ.jpg"},
        {"title": "Eat Smart, Think Smart", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0060170441.01.MZZZZZZZ.jpg"},
        {"title": "Negaholics", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0712646221.01.MZZZZZZZ.jpg"},
        {"title": "Third Eye", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0440987202.01.MZZZZZZZ.jpg"},
        {"title": "Sympathy for the Devil", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0380795965.01.MZZZZZZZ.jpg"},
        {"title": "Reviving Ophelia", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0345392825.01.MZZZZZZZ.jpg"},
        {"title": "Seven Habits of Highly Effective People", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0671708635.01.MZZZZZZZ.jpg"},
        {"title": "Chicken Soup for the College Soul", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/1558747028.01.MZZZZZZZ.jpg"},
        {"title": "You're Fifty--Now What", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0609605623.01.MZZZZZZZ.jpg"},
        {"title": "Emotional Purity", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/1579213405.01.MZZZZZZZ.jpg"},
        {"title": "Feeling Good", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0688036333.01.MZZZZZZZ.jpg"},
        {"title": "The Big Book of Calm", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0140282378.01.MZZZZZZZ.jpg"},
        {"title": "What Women Want", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/037303752X.01.MZZZZZZZ.jpg"},
        {"title": "The Self-Esteem Companion", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/1572241381.01.MZZZZZZZ.jpg"},
        {"title": "Becoming a Critical Thinker", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/0130289221.01.MZZZZZZZ.jpg"},
        {"title": "How to Say It Style Guide", "genre": "Motivational", "image_url": "http://images.amazon.com/images/P/073520313X.01.MZZZZZZZ.jpg"},
        {"title": "Sophie's World: A Novel About the History of Philosophy", "genre": "Philosophical", "image_url": "http://images.amazon.com/images/P/3423620005.01.MZZZZZZZ.jpg"},
        {"title": "Common Phrases: And Where They Come From", "genre": "Philosophical", "image_url": "http://images.amazon.com/images/P/1585746827.01.MZZZZZZZ.jpg"},
        {"title": "The Brothers Karamazov", "genre": "Philosophical", "image_url": "http://images.amazon.com/images/P/0865474222.01.MZZZZZZZ.jpg"},
        {"title": "Fahrenheit 451", "genre": "Philosophical", "image_url": "http://images.amazon.com/images/P/0881030198.01.MZZZZZZZ.jpg"},
        {"title": "The Little Prince", "genre": "Philosophical", "image_url": "http://images.amazon.com/images/P/0156528207.01.MZZZZZZZ.jpg"},
        {"title": "Atlas Shrugged", "genre": "Philosophical", "image_url": "http://images.amazon.com/images/P/0451191145.01.MZZZZZZZ.jpg"},
        {"title": "The Myth of Sisyphus and Other Essays (Vintage International)", "genre": "Philosophical", "image_url": "http://images.amazon.com/images/P/0679733736.01.MZZZZZZZ.jpg"},
        {"title": "The Selfish Gene", "genre": "Philosophical", "image_url": "http://images.amazon.com/images/P/0192860925.01.MZZZZZZZ.jpg"},
        {"title": "Siddhartha: An Indian Tale (Penguin Classics)", "genre": "Philosophical", "image_url": "http://images.amazon.com/images/P/0142437182.01.MZZZZZZZ.jpg"},
        {"title": "1984", "genre": "Philosophical", "image_url": "http://images.amazon.com/images/P/0704339838.01.MZZZZZZZ.jpg"},
        {"title": "The Picture of Dorian Gray", "genre": "Philosophical", "image_url": "http://images.amazon.com/images/P/0893759953.01.MZZZZZZZ.jpg"},
        {"title": "Anam Cara", "genre": "Spiritual", "image_url": "http://images.amazon.com/images/P/0060182792.01.MZZZZZZZ.jpg"},
    ],
}

# Insert books into the database
for emotion, book_list in books.items():
    collection = db[emotion]
    collection.insert_many(book_list)

print("Books for each emotion have been inserted successfully!")